import type { CollectionDataSource, ID } from "@/lib/db/adapters";
import type { Coupon } from "@/types";

/**
 * Coupon repository encapsulates CRUD operations and common lookups
 * for coupons, based on the Coupon type definition.
 */
export function createCouponRepository(dataSoure: CollectionDataSource){

    const collection = "coupons";

    return {
          /**
     * Get all coupons.
     */
       async getAll(): Promise<Coupon[]> {
         return dataSoure.read<Coupon>(collection);
       },

        /**
     * Get a coupon by id.
     */
      
       async getById(id: ID) : Promise<Coupon | null> {
         return dataSoure.get<Coupon>(collection, id);
       },

        /**
     * Get a coupon by its unique code (case-insensitive).
     */
       async getByCode(code: string) : Promise<Coupon | null> {
        const all = await dataSoure.read<Coupon>(collection);
        return all.find((c) => c.code.toLowerCase() === code.toLowerCase()) ?? null;
       },

         /**
     * Create a new coupon.
     * Id will be generated by the underlying data source if missing.
     */

         async create(coupon: Omit<Coupon, "id">): Promise<Coupon> {
            return dataSoure.upsert<Coupon>(collection, coupon as Coupon);
         },

          /**
     * Update an existing coupon (requires id).
     */
        async update(coupon: Coupon) : Promise<Coupon> {
            if(!coupon.id && coupon.id !== 0){
                throw new Error("Coupon id is required for update");
            }
            return dataSoure.upsert<Coupon>(collection, coupon)
        },

        /**
     * Delete a coupon by id.
     */
       
        async delete(id: ID): Promise<boolean> {
            return dataSoure.delete(collection, id);
        },

         /**
     * Increment usedCount for a coupon by id.
     * Enforces maxUsage if present.
     */

          async incrementUsage(id: ID): Promise<Coupon> {
            const existing = await dataSoure.get<Coupon>(collection, id);
            if(!existing) throw new Error("Coupon not found");

            const used = existing.usedCount ?? 0;
            const max = existing.maxUsage ?? undefined;

            if(typeof max === "number" && used >= max){
                throw new Error("Coupon usage limit reached");
            }

            const updated: Coupon = {
                ...existing,
                usedCount: used + 1,
            };

            return dataSoure.upsert<Coupon>(collection, updated);
          },

           /**
     * Toggle coupon enabled flag.
     */

            async setEnabled(id: ID, enabled: boolean): Promise<Coupon> {
                const existing = await dataSoure.get<Coupon>(collection, id);
                if(!existing) throw new Error("Coupon not found");

                const updated: Coupon = {
                    ...existing,
                    enabled,
                };

                return dataSoure.upsert<Coupon>(collection, updated);
            },

    };
}